local builtin = require("telescope.builtin")
vim.keymap.set("n", "ff", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "fg", builtin.live_grep, { desc = "Telescope live grep" })
vim.keymap.set("n", "bb", builtin.buffers, { desc = "Telescope buffers" })
vim.keymap.set("n", "fh", builtin.help_tags, { desc = "Telescope help tags" })
